language: ruby
rvm:
  - 2.2.2

env:
  - DB=postgresql

script:
  - bundle exec rake db:reset RAILS_ENV=test
  - COVERALLS=true bundle exec rake test

before_script:
  - cp config/database.ci.yml config/database.yml
  - cp config/application.ci.yml config/application.yml
  - cp config/initializers/secret_token.ci.rb config/initializers/secret_token.rb
  - bundle exec rake db:create RAILS_ENV=test