# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a80ef95ba04cf564925ed0f2845d19f580a4efdce31a6ccda245f881bfd38c3df709d41c9f4d275c58f7ccc7f9f9b305186b1101a2e63563ec9523dbd760606

test:
  secret_key_base: aadb06820dc9e3016ef6704943f9051ca8bd7441d88ff4154eff2203a3c521bfc34969205b3f28bf3f997b2932c6e93351f7577f350f31d6a8f58f4b7dbe8562

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
